#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi

if [ "$branch" = "develop" ]; then
  echo "You can't commit directly to develop branch"
  exit 1
fi

if [ "$branch" = "homolog" ]; then
  echo "You can't commit directly to homolog branch"
  exit 1
fi

npx lint-staged
